### ISSUE TITLE
Cannot get this working with groups

### ISSUE THREAD

**Issue by BNWEIN** [AlessandroSpallina/EthermineTelegramBots#1]
Works really well when talking directly to me, but even after adding the group ID in it wont work with a group.

**Comment by AlessandroSpallina** [comment]
Are you sure? Because I use it in a group

**Comment by BNWEIN** [comment]
I got it working. My mistake. Thanks. 

It wasnt clear there was a "-" at the beginning of a group ID

**Comment by AlessandroSpallina** [comment]
:)
